#!/bin/sh
unset NODE_OPTIONS
ELECTRON_RUN_AS_NODE=1 "/nix/store/dck1mlz2mqw4r0wlzigzzimkrqgggp1g-vscode-1.97.0/lib/vscode/code" "/home/leob/.config/Code/User/globalStorage/github.copilot-chat/debugCommand/copilotDebugCommand.js" "vscode://github.copilot-chat" "" "$@"